### ISSUE TITLE
How to get a list of sensors/pumps etc. from the Resol 

### ISSUE THREAD

**Issue by epenet** [epenet/hassResolVbus#5]
Now to figure out how to get a list of sensors/pumps etc. from the Resol device to buld the HASS config.
I used the examples you provided but I just get Temperature 1 None C and Pump 1 None%.

_Originally posted by @craigueh in https://github.com/epenet/hassResolVbus/issues/3#issuecomment-527982550_

**Comment by epenet** [comment]
Hi @craigueh,

What device do you have? Did you check the [Resol Specification](https://github.com/epenet/pyvbus/blob/master/documentation/VBus%20Protocol%20Specification%20-%20English%202011-01-27.pdf)?
My settings are based on a Vitosolic 200 (device code 0x7321 on page 51), but you might not have a Vitosolic 200.

**Comment by craggyh** [comment]
No I have the DeltaSol BS (0x3251). I changed the config to this but it doesn't seem to help.
Is there a log file somewhere I could see if it's actually running/connecting to the serial port?

**Comment by epenet** [comment]
As per the [main hass documentation](https://www.home-assistant.io/components/logger/) You can tweak your main configuration file (logger section) to enable debug on specific components.

This worked until HASS 0.88:
```
logger:
  default: warn
  logs:
    custom_components.sensor.resolvbus: debug
```

Since HASS 0.88, I think you need to write it like this (untested):
```
logger:
  default: warn
  logs:
    custom_components.resolvbus: debug
```
